### ISSUE TITLE
0.2.0 Endgame

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-dependency#107]
# Summary
1. the target date for this release will be 11/16
2. Fix the following issues:
  - [x] #79 Files in 'src/main/resources/' do not display enhancement
  - [x] #83  The side bar keeps popping up when a new Java file opens
  - [x] #80  No way to link a java class definition back to the project explorer?
3. Left over issues:
  - #106 No way to link a resource files back to the project explorer
  - JDK class may not link back to the project explorer
  - No outline for .class in jar without source

# Build 
- [x]  11/19 - Bump version to 0.2.0 @andxu
- [x]  11/19 - Add change log for 0.2.0 - @andxu
- [x]  11/19- Signed RC Bits @andxu  https://vscjavaci.cloudapp.net/job/vscode-java-dependency/job/vscode-java-dependency.vsix.withSign/12/

# Test
- [x] 11/19 - Run test plan and verify bugs listed in 0.2.0 milestone(windows and mac) - @

# Release
- [x] 11/19 - Add 0.2.0 tag  - @andxu
- [x] 11/19 - Release to marketplace - @andxu

# Notes
Before you check an item, please reply to this issue with the following details:

What are the steps and details of your check?
What are the configurations?
What are the issues found in the process?
What's your conclusion?

**Comment by lxhmavis** [comment]
### Run Test Plan

1. Build:12
2. Open bugs:
#110 #111  #112 
4. Run test plan result:

Project | Win | Mac
-- | -- | --
Install | Pass | Pass
Uninstall | Pass | Pass
Basic | Pass | Pass
Simple project | #112  | Pass
Maven project | Pass | Pass
Gradle project | Pass | Pass
Multiple project | #111  | Pass
Telemetry


5. Test new feature

Feature | Win | Mac
-- | -- | --
The side bar keeps   popping up when a new Java file opens | Pass | Pass
Can   show"Files in 'src/main/resources/'" | Pass | Pass
No way to link a   java class definition back to the project explorer | #110 | #110
