### ISSUE TITLE
0.3.0 Endgame

### ISSUE THREAD

**Issue by andxu** [Microsoft/vscode-java-dependency#133]
# Summary
1. the target date for this release will be 12/21
2. Fix the following issues:
  - [ ] #106 No way to link a resource files back to the project explorer
  - [ ] #100 Chinese Language Support 
  - [ ] #99  The cursor jumps is not accurate if there are comments
  - [ ] #110 The link can open in the page but the left bar can't open for JDK classes
  - [ ] #14 Different lib jars will be displayed as independent package container 
  - [ ] #111 It will pop errors when open the libraries in Multiple-project 
  - [ ] #35 Class file can't show the symbols in the explorers
  - [ ] #77 No JAVA PACKAGES explorer sidebar on symlink folders

# Build 
- [x]  12/21 - Bump version to 0.3.0 @andxu
- [x]  12/21 - Add change log for 0.3.0 - @andxu
- [x]  12/21- Signed RC Bits @andxu  https://vscjavaci.cloudapp.net/job/vscode-java-dependency/job/vscode-java-dependency.vsix.withSign/

# Test
- [x] 12/21 - Run test plan and verify bugs listed in 0.3.0 milestone(windows and mac) - @

# Release
- [x] 12/21 - Add 0.3.0 tag  - @andxu
- [x] 12/21 - Release to marketplace - @andxu

# Notes
Before you check an item, please reply to this issue with the following details:

What are the steps and details of your check?
What are the configurations?
What are the issues found in the process?
What's your conclusion?

**Comment by lxhmavis** [comment]
### Run test plan

**1. Configuration**

Windows | Mac
-- | --
Vscode 1.301 JDK 8 | Vscode1.30.1 JDK 11

**2. Open Bug**

#137

**3. Test result**

Fixed bugs:

No. | Test case | Windows  | Mac
-- | -- | -- | --
1 | No way to link a   resource files back to the project explorer #106 | Pass | Pass
2 | Chinese Language   Support #100 | Pass | /
3 | The cursor jumps is   not accurate if there are comments #99 | Pass | Pass
4 | The link can open   in the page but the left bar can't open for JDK classes #110 | Pass | Pass
5 | Different lib jars   will be displayed as independent package container #14 | Pass | Pass
6 | It will pop   errors when open the libraries in Multiple-project #111 | Pass | Pass
7 | Class file can't   show the symbols in the explorers #35 | Pass | Pass
8 | No JAVA PACKAGES   explorer sidebar on symlink folders #77 | Pass | Pass


Run test plan:

Test case | Windows | Mac
-- | -- | --
Clean install | Pass | pass
Update | Pass | pass
Uninstall | Pass | pass
Basic | Pass | pass
Simple project | Pass | pass
Maven project | Pass | pass
Gradle project | Pass | pass
Multiple project | Pass | pass
Telemetry | Pass | Pass
Activation time | Basic project: 35ms  Simple project: 35ms   Maven project: 29ms   Gradle project: 41ms   Multiple project: 39ms | Basic project: 50ms   Simple project: 50ms   Maven project: 35ms   Gradle project: 43ms   Multiple project: 42ms
Can show" Files   in 'src/main/resources/' " | #137 | #137
No way to link a   java class definition back to the project explorer | Pass | Pass
